// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AnalysisUpdaterController from "./analysis_updater_controller"
application.register("analysis-updater", AnalysisUpdaterController)

import ChartController from "./chart_controller"
application.register("chart", ChartController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import WebAudioRecorderController from "./web_audio_recorder_controller"
application.register("web-audio-recorder", WebAudioRecorderController)
