# fly.toml app configuration file generated for voicebloom-api on 2025-05-19T21:33:28+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app            = "voicebloom-api"
primary_region = "nrt"

[build]
  context    = "."
  dockerfile = "Dockerfile.python"

[env]
  PORT       = "8000"
  PYTHON_ENV = "production"

[processes]
  app = "uvicorn main:app --host 0.0.0.0 --port ${PORT} --workers 1 --app-dir /app/python_api"

[http_service]
  internal_port        = 8000
  force_https          = true
  auto_stop_machines   = "stop"
  auto_start_machines  = true
  min_machines_running = 0
  processes            = ["app"]

  [[http_service.checks]]
    port         = 8000
    path         = "/health"
    interval     = "10s"
    timeout      = "2s"
    grace_period = "10s"

[[vm]]
  size = "shared-cpu-1x"
