version: '3.8'
services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: 'Asia/Tokyo'

  web:
    build:
      context: .
      dockerfile: Dockerfile.rails
      target: development
    working_dir: /app
    command: bash -c "bundle exec rails db:prepare && rm -f tmp/pids/server.pid && ./bin/dev"
    volumes:
      - .:/app
      - bundle_cache:/app/vendor/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/voice_bloom_development
      FASTAPI_URL: 'http://api:8000'
      RAILS_ENV: development
      TZ: 'Asia/Tokyo'

  api:
    build:
      context: ./python_api
      dockerfile: Dockerfile.python
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --app-dir /app/python_api
    volumes:
      - ./python_api:/app/python_api
    ports:
      - "8000:8000"
    environment:
      PYTHON_ENV: development

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  bundle_cache:
  redis_data: