ARG PYTHON_VERSION=3.11
FROM python:$PYTHON_VERSION-slim

WORKDIR /app/python_api

COPY ./python_api/requirements.txt /app/python_api/
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY ./python_api /app/python_api

EXPOSE 8000