# fly.toml app configuration file generated for voicebloom-dev on 2025-05-19T21:12:33+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app             = "voicebloom-dev"
primary_region  = "nrt"
console_command = "/rails/bin/rails console"

[build]
  dockerfile = "Dockerfile.rails"

[env]
  PORT                     = "3000"
  RAILS_LOG_TO_STDOUT      = "true"
  RAILS_SERVE_STATIC_FILES = "true"
  RAILS_ENV                = "production"

[processes]
  app = "bundle exec puma -C config/puma.rb"

[deploy]
  release_command = "./bin/rails db:prepare"

[http_service]
  internal_port        = 3000
  force_https          = true
  auto_stop_machines   = "stop"
  auto_start_machines  = true
  min_machines_running = 1
  processes            = ["app"]

  [[http_service.checks]]
    path = "/up"

# 静的ファイル配信設定
[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"

[[vm]]
  size = "shared-cpu-1x"
